# These are provided in Android-based builds
# Need to explicitly define for Kernel-based builds
MODNAME := wlan

# Module information used by KBuild framework
obj-$(CONFIG_VOLANS_WLAN) += $(MODNAME).o
$(MODNAME)-y := volans_wlan.o__shipped
