# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
# headset detect switch
obj-$(CONFIG_LGE_SWITCH_GPIO)	+= lge_gpio_switch.o
obj-$(CONFIG_LGE_HEADSET_DETECTION_FSA8008) += fsa8008.o
