obj-$(CONFIG_MACH_MSM7X25A_E0EU) += bosch_sensors.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += gpio_keypad.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += gpio_earsense.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += proximity_gp2ap.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += touchscreen-mms128.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += pmic_leds.o
